# Generated by Django 4.0.6 on 2022-07-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protesteaqui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='idade',
            field=models.IntegerField(default=0),
        ),
    ]
