# Generated by Django 4.0.6 on 2022-07-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protesteaqui', '0002_professor_idade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
