# Generated by Django 4.0.6 on 2022-07-27 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protesteaqui', '0003_alter_professor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=600)),
                ('nota', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'professores'},
        ),
    ]
