# Generated by Django 4.0.6 on 2022-07-27 14:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protesteaqui', '0004_avaliacao_alter_professor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='professor_refe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='protesteaqui.professor'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
